# Generated by Django 3.0.5 on 2020-04-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
